[mongo]
host = "mongodb+srv://hmaurya416:harsh1234@cluster1.2nqczem.mongodb.net/?retryWrites=true&w=majority&appName=Cluster1"
username = "hmaurya416"
password = "harsh1234"
database = "c"
collection = "students"